6. お問い合わせフォームを修正しよう
yuta10200831/6-1.docker-template pull request #6
Opened 2023-08-27 11:18 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/6-8aa5380343ef44d3b59e9c04691a27a1
[作成したページのURL(index.php)]
<img width="1714" alt="スクリーンショット 2023-08-27 20 14 53" src="https://github.com/yuta10200831/6-1.docker-template/assets/124555669/f49dca4c-f547-409a-90ff-3dfdeb018322">

## 作業詳細
以前作成したお問い合わせフォームの修正をしましょう。
CSSフレームワークTailwindを使って見た目を整えましょう。
(Tailwindの使い方は調べましょう)

2023-08-27 16:02 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-08-27 16:02 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +<head>
こんな感じで地図が入るようにしましょう！！
<img width="379" alt="スクリーンショット 2023-08-28 1 00 27" src="https://github.com/yuta10200831/6-1.docker-template/assets/63081802/99524e2c-959f-4209-85fd-9ecb7a2e1590">

2023-08-28 09:50 UTC, yuta10200831 commented on src/public/index.php
> +<head>
修正済み

2023-08-28 09:52 UTC, yuta10200831 commented
背景に画像が来るように修正いたしました！
ご確認宜しくお願い致します。

<img width="1714" alt="スクリーンショット 2023-08-28 18 51 34" src="https://github.com/yuta10200831/6-1.docker-template/assets/124555669/66593262-2c6f-4f02-904a-1bc5347df069">

2023-08-29 03:31 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-31 09:50 UTC, merged